package com.example.demo.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@ToString
@Builder
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "users")
public class User {

    @DynamoDBHashKey(attributeName = "userID")
    @DynamoDBAutoGeneratedKey
    public String userID;

    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBAttribute(attributeName = "password")
    private String password;

    @DynamoDBAttribute(attributeName = "userType")
    @DynamoDBTypeConverted(converter = UserTypeTranslator.class)
    private UserType userType;

    @DynamoDBAttribute(attributeName = "dailyLimit")
    private int dailyLimit;
}
